import { NextResponse } from 'next/server';

// List of all 114 Surahs with their details
const surahs = [
  { number: 1, name: 'الفاتحة', transliteration: 'Al-Fatihah', translation: 'Pembukaan', totalVerses: 7, revelation: 'Makkah' },
  { number: 2, name: 'البقرة', transliteration: 'Al-Baqarah', translation: 'Sapi Betina', totalVerses: 286, revelation: 'Madinah' },
  { number: 3, name: 'آل عمران', transliteration: 'Ali \'Imran', translation: 'Keluarga Imran', totalVerses: 200, revelation: 'Madinah' },
  { number: 4, name: 'النساء', transliteration: 'An-Nisa', translation: 'Wanita', totalVerses: 176, revelation: 'Madinah' },
  { number: 5, name: 'المائدة', transliteration: 'Al-Ma\'idah', translation: 'Hidangan', totalVerses: 120, revelation: 'Madinah' },
  { number: 6, name: 'الأنعام', transliteration: 'Al-An\'am', translation: 'Binatang Ternak', totalVerses: 165, revelation: 'Makkah' },
  { number: 7, name: 'الأعراف', transliteration: 'Al-A\'raf', translation: 'Tempat Tertinggi', totalVerses: 206, revelation: 'Makkah' },
  { number: 8, name: 'الأنفال', transliteration: 'Al-Anfal', translation: 'Harta Rampasan Perang', totalVerses: 75, revelation: 'Madinah' },
  { number: 9, name: 'التوبة', transliteration: 'At-Taubah', translation: 'Pengampunan', totalVerses: 129, revelation: 'Madinah' },
  { number: 10, name: 'يونس', transliteration: 'Yunus', translation: 'Yunus', totalVerses: 109, revelation: 'Makkah' },
  { number: 11, name: 'هود', transliteration: 'Hud', translation: 'Hud', totalVerses: 123, revelation: 'Makkah' },
  { number: 12, name: 'يوسف', transliteration: 'Yusuf', translation: 'Yusuf', totalVerses: 111, revelation: 'Makkah' },
  { number: 13, name: 'الرعد', transliteration: 'Ar-Ra\'d', translation: 'Guruh', totalVerses: 43, revelation: 'Madinah' },
  { number: 14, name: 'ابراهيم', transliteration: 'Ibrahim', translation: 'Ibrahim', totalVerses: 52, revelation: 'Makkah' },
  { number: 15, name: 'الحجر', transliteration: 'Al-Hijr', translation: 'Hijr', totalVerses: 99, revelation: 'Makkah' },
  { number: 16, name: 'النحل', transliteration: 'An-Nahl', translation: 'Lebah', totalVerses: 128, revelation: 'Makkah' },
  { number: 17, name: 'الإسراء', transliteration: 'Al-Isra', translation: 'Perjalanan Malam', totalVerses: 111, revelation: 'Makkah' },
  { number: 18, name: 'الكهف', transliteration: 'Al-Kahf', translation: 'Gua', totalVerses: 110, revelation: 'Makkah' },
  { number: 19, name: 'مريم', transliteration: 'Maryam', translation: 'Maryam', totalVerses: 98, revelation: 'Makkah' },
  { number: 20, name: 'طه', transliteration: 'Taha', translation: 'Taha', totalVerses: 135, revelation: 'Makkah' },
  { number: 21, name: 'الأنبياء', transliteration: 'Al-Anbya', translation: 'Para Nabi', totalVerses: 112, revelation: 'Makkah' },
  { number: 22, name: 'الحج', transliteration: 'Al-Hajj', translation: 'Haji', totalVerses: 78, revelation: 'Madinah' },
  { number: 23, name: 'المؤمنون', transliteration: 'Al-Mu\'minun', translation: 'Orang-orang Mukmin', totalVerses: 118, revelation: 'Makkah' },
  { number: 24, name: 'النور', transliteration: 'An-Nur', translation: 'Cahaya', totalVerses: 64, revelation: 'Madinah' },
  { number: 25, name: 'الفرقان', transliteration: 'Al-Furqan', translation: 'Pembeda', totalVerses: 77, revelation: 'Makkah' },
  { number: 26, name: 'الشعراء', transliteration: 'Asy-Syu\'ara', translation: 'Penyair', totalVerses: 227, revelation: 'Makkah' },
  { number: 27, name: 'النمل', transliteration: 'An-Naml', translation: 'Semut', totalVerses: 93, revelation: 'Makkah' },
  { number: 28, name: 'القصص', transliteration: 'Al-Qasas', translation: 'Kisah-kisah', totalVerses: 88, revelation: 'Makkah' },
  { number: 29, name: 'العنكبوت', transliteration: 'Al-\'Ankabut', translation: 'Laba-laba', totalVerses: 69, revelation: 'Makkah' },
  { number: 30, name: 'الروم', transliteration: 'Ar-Rum', translation: 'Romawi', totalVerses: 60, revelation: 'Makkah' },
  { number: 31, name: 'لقمان', transliteration: 'Luqman', translation: 'Luqman', totalVerses: 34, revelation: 'Makkah' },
  { number: 32, name: 'السجدة', transliteration: 'As-Sajdah', translation: 'Sajdah', totalVerses: 30, revelation: 'Makkah' },
  { number: 33, name: 'الأحزاب', transliteration: 'Al-Ahzab', translation: 'Golongan-golongan', totalVerses: 73, revelation: 'Madinah' },
  { number: 34, name: 'سبإ', transliteration: 'Saba', translation: 'Saba', totalVerses: 54, revelation: 'Makkah' },
  { number: 35, name: 'فاطر', transliteration: 'Fatir', translation: 'Pencipta', totalVerses: 45, revelation: 'Makkah' },
  { number: 36, name: 'يس', transliteration: 'Ya-Sin', translation: 'Ya-Sin', totalVerses: 83, revelation: 'Makkah' },
  { number: 37, name: 'الصافات', transliteration: 'As-Saffat', translation: 'Barisan-barisan', totalVerses: 182, revelation: 'Makkah' },
  { number: 38, name: 'ص', transliteration: 'Sad', translation: 'Sad', totalVerses: 88, revelation: 'Makkah' },
  { number: 39, name: 'الزمر', transliteration: 'Az-Zumar', translation: 'Rombongan', totalVerses: 75, revelation: 'Makkah' },
  { number: 40, name: 'غافر', transliteration: 'Ghafir', translation: 'Yang Mengampuni', totalVerses: 85, revelation: 'Makkah' },
  { number: 41, name: 'فصلت', transliteration: 'Fussilat', translation: 'Dijelaskan', totalVerses: 54, revelation: 'Makkah' },
  { number: 42, name: 'الشورى', transliteration: 'Asy-Syura', translation: 'Musyawarah', totalVerses: 53, revelation: 'Makkah' },
  { number: 43, name: 'الزخرف', transliteration: 'Az-Zukhruf', translation: 'Perhiasan', totalVerses: 89, revelation: 'Makkah' },
  { number: 44, name: 'الدخان', transliteration: 'Ad-Dukhan', translation: 'Kabut', totalVerses: 59, revelation: 'Makkah' },
  { number: 45, name: 'الجاثية', transliteration: 'Al-Jasiyah', translation: 'Berlutut', totalVerses: 37, revelation: 'Makkah' },
  { number: 46, name: 'الأحقاف', transliteration: 'Al-Ahqaf', translation: 'Bukit Pasir', totalVerses: 35, revelation: 'Makkah' },
  { number: 47, name: 'محمد', transliteration: 'Muhammad', translation: 'Muhammad', totalVerses: 38, revelation: 'Madinah' },
  { number: 48, name: 'الفتح', transliteration: 'Al-Fath', translation: 'Kemenangan', totalVerses: 29, revelation: 'Madinah' },
  { number: 49, name: 'الحجرات', transliteration: 'Al-Hujurat', translation: 'Kamar-kamar', totalVerses: 18, revelation: 'Madinah' },
  { number: 50, name: 'ق', transliteration: 'Qaf', translation: 'Qaf', totalVerses: 45, revelation: 'Makkah' },
  { number: 51, name: 'الذاريات', transliteration: 'Az-Zariyat', translation: 'Angin', totalVerses: 60, revelation: 'Makkah' },
  { number: 52, name: 'الطور', transliteration: 'At-Tur', translation: 'Bukit Tursina', totalVerses: 49, revelation: 'Makkah' },
  { number: 53, name: 'النجم', transliteration: 'An-Najm', translation: 'Bintang', totalVerses: 62, revelation: 'Makkah' },
  { number: 54, name: 'القمر', transliteration: 'Al-Qamar', translation: 'Bulan', totalVerses: 55, revelation: 'Makkah' },
  { number: 55, name: 'الرحمن', transliteration: 'Ar-Rahman', translation: 'Maha Pengasih', totalVerses: 78, revelation: 'Madinah' },
  { number: 56, name: 'الواقعة', transliteration: 'Al-Waqi\'ah', translation: 'Hari Kiamat', totalVerses: 96, revelation: 'Makkah' },
  { number: 57, name: 'الحديد', transliteration: 'Al-Hadid', translation: 'Besi', totalVerses: 29, revelation: 'Madinah' },
  { number: 58, name: 'المجادلة', transliteration: 'Al-Mujadilah', translation: 'Gugatan', totalVerses: 22, revelation: 'Madinah' },
  { number: 59, name: 'الحشر', transliteration: 'Al-Hasyr', translation: 'Pengusiran', totalVerses: 24, revelation: 'Madinah' },
  { number: 60, name: 'الممتحنة', transliteration: 'Al-Mumtahanah', translation: 'Wanita yang Diuji', totalVerses: 13, revelation: 'Madinah' },
  { number: 61, name: 'الصف', transliteration: 'As-Saff', translation: 'Barisan', totalVerses: 14, revelation: 'Madinah' },
  { number: 62, name: 'الجمعة', transliteration: 'Al-Jumu\'ah', translation: 'Jumat', totalVerses: 11, revelation: 'Madinah' },
  { number: 63, name: 'المنافقون', transliteration: 'Al-Munafiqun', translation: 'Orang-orang Munafik', totalVerses: 11, revelation: 'Madinah' },
  { number: 64, name: 'التغابن', transliteration: 'At-Taghabun', translation: 'Hari Dinampakkan Kesalahan', totalVerses: 18, revelation: 'Madinah' },
  { number: 65, name: 'الطلاق', transliteration: 'At-Talaq', translation: 'Talak', totalVerses: 12, revelation: 'Madinah' },
  { number: 66, name: 'التحريم', transliteration: 'At-Tahrim', translation: 'Pengharaman', totalVerses: 12, revelation: 'Madinah' },
  { number: 67, name: 'الملك', transliteration: 'Al-Mulk', translation: 'Kerajaan', totalVerses: 30, revelation: 'Makkah' },
  { number: 68, name: 'القلم', transliteration: 'Al-Qalam', translation: 'Pena', totalVerses: 52, revelation: 'Makkah' },
  { number: 69, name: 'الحاقة', transliteration: 'Al-Haqqah', translation: 'Hari Kiamat', totalVerses: 52, revelation: 'Makkah' },
  { number: 70, name: 'المعارج', transliteration: 'Al-Ma\'arij', translation: 'Tempat Naik', totalVerses: 44, revelation: 'Makkah' },
  { number: 71, name: 'نوح', transliteration: 'Nuh', translation: 'Nuh', totalVerses: 28, revelation: 'Makkah' },
  { number: 72, name: 'الجن', transliteration: 'Al-Jinn', translation: 'Jin', totalVerses: 28, revelation: 'Makkah' },
  { number: 73, name: 'المزمل', transliteration: 'Al-Muzzammil', translation: 'Orang yang Berselimut', totalVerses: 20, revelation: 'Makkah' },
  { number: 74, name: 'المدثر', transliteration: 'Al-Muddassir', translation: 'Orang yang Berkemul', totalVerses: 56, revelation: 'Makkah' },
  { number: 75, name: 'القيامة', transliteration: 'Al-Qiyamah', translation: 'Hari Kiamat', totalVerses: 40, revelation: 'Makkah' },
  { number: 76, name: 'الانسان', transliteration: 'Al-Insan', translation: 'Manusia', totalVerses: 31, revelation: 'Madinah' },
  { number: 77, name: 'المرسلات', transliteration: 'Al-Mursalat', translation: 'Malaikat yang Diutus', totalVerses: 50, revelation: 'Makkah' },
  { number: 78, name: 'النبإ', transliteration: 'An-Naba', translation: 'Berita Besar', totalVerses: 40, revelation: 'Makkah' },
  { number: 79, name: 'النازعات', transliteration: 'An-Nazi\'at', translation: 'Malaikat yang Mencabut', totalVerses: 46, revelation: 'Makkah' },
  { number: 80, name: 'عبس', transliteration: '\'Abasa', translation: 'Bermuka Masam', totalVerses: 42, revelation: 'Makkah' },
  { number: 81, name: 'التكوير', transliteration: 'At-Takwir', translation: 'Menggulung', totalVerses: 29, revelation: 'Makkah' },
  { number: 82, name: 'الإنفطار', transliteration: 'Al-Infitar', translation: 'Terbelah', totalVerses: 19, revelation: 'Makkah' },
  { number: 83, name: 'المطففين', transliteration: 'Al-Mutaffifin', translation: 'Orang Curang', totalVerses: 36, revelation: 'Makkah' },
  { number: 84, name: 'الإنشقاق', transliteration: 'Al-Insyiqaq', translation: 'Terbelah', totalVerses: 25, revelation: 'Makkah' },
  { number: 85, name: 'البروج', transliteration: 'Al-Buruj', translation: 'Gugusan Bintang', totalVerses: 22, revelation: 'Makkah' },
  { number: 86, name: 'الطارق', transliteration: 'At-Tariq', translation: 'Yang Datang di Malam Hari', totalVerses: 17, revelation: 'Makkah' },
  { number: 87, name: 'الأعلى', transliteration: 'Al-A\'la', translation: 'Maha Tinggi', totalVerses: 19, revelation: 'Makkah' },
  { number: 88, name: 'الغاشية', transliteration: 'Al-Ghasyiyah', translation: 'Hari Pembalasan', totalVerses: 26, revelation: 'Makkah' },
  { number: 89, name: 'الفجر', transliteration: 'Al-Fajr', translation: 'Fajar', totalVerses: 30, revelation: 'Makkah' },
  { number: 90, name: 'البلد', transliteration: 'Al-Balad', translation: 'Negeri', totalVerses: 20, revelation: 'Makkah' },
  { number: 91, name: 'الشمس', transliteration: 'Asy-Syams', translation: 'Matahari', totalVerses: 15, revelation: 'Makkah' },
  { number: 92, name: 'الليل', transliteration: 'Al-Lail', translation: 'Malam', totalVerses: 21, revelation: 'Makkah' },
  { number: 93, name: 'الضحى', transliteration: 'Ad-Duha', translation: 'Duha', totalVerses: 11, revelation: 'Makkah' },
  { number: 94, name: 'الشرح', transliteration: 'Asy-Syarh', translation: 'Kelapangan', totalVerses: 8, revelation: 'Makkah' },
  { number: 95, name: 'التين', transliteration: 'At-Tin', translation: 'Buah Tin', totalVerses: 8, revelation: 'Makkah' },
  { number: 96, name: 'العلق', transliteration: 'Al-\'Alaq', translation: 'Segumpal Darah', totalVerses: 19, revelation: 'Makkah' },
  { number: 97, name: 'القدر', transliteration: 'Al-Qadr', translation: 'Kemuliaan', totalVerses: 5, revelation: 'Makkah' },
  { number: 98, name: 'البينة', transliteration: 'Al-Bayyinah', translation: 'Bukti', totalVerses: 8, revelation: 'Madinah' },
  { number: 99, name: 'الزلزلة', transliteration: 'Az-Zalzalah', translation: 'Guncangan', totalVerses: 8, revelation: 'Madinah' },
  { number: 100, name: 'العاديات', transliteration: 'Al-\'Adiyat', translation: 'Kuda Perang', totalVerses: 11, revelation: 'Makkah' },
  { number: 101, name: 'القارعة', transliteration: 'Al-Qari\'ah', translation: 'Hari Kiamat', totalVerses: 11, revelation: 'Makkah' },
  { number: 102, name: 'التكاثر', transliteration: 'At-Takasur', translation: 'Bermegah-megahan', totalVerses: 8, revelation: 'Makkah' },
  { number: 103, name: 'العصر', transliteration: 'Al-\'Asr', translation: 'Masa', totalVerses: 3, revelation: 'Makkah' },
  { number: 104, name: 'الهمزة', transliteration: 'Al-Humazah', translation: 'Pengumpat', totalVerses: 9, revelation: 'Makkah' },
  { number: 105, name: 'الفيل', transliteration: 'Al-Fil', translation: 'Gajah', totalVerses: 5, revelation: 'Makkah' },
  { number: 106, name: 'قريش', transliteration: 'Quraisy', translation: 'Quraisy', totalVerses: 4, revelation: 'Makkah' },
  { number: 107, name: 'الماعون', transliteration: 'Al-Ma\'un', translation: 'Barang Berguna', totalVerses: 7, revelation: 'Makkah' },
  { number: 108, name: 'الكوثر', transliteration: 'Al-Kausar', translation: 'Nikmat yang Berlimpah', totalVerses: 3, revelation: 'Makkah' },
  { number: 109, name: 'الكافرون', transliteration: 'Al-Kafirun', translation: 'Orang-orang Kafir', totalVerses: 6, revelation: 'Makkah' },
  { number: 110, name: 'النصر', transliteration: 'An-Nasr', translation: 'Pertolongan', totalVerses: 3, revelation: 'Madinah' },
  { number: 111, name: 'المسد', transliteration: 'Al-Masad', translation: 'Api yang Bergejolak', totalVerses: 5, revelation: 'Makkah' },
  { number: 112, name: 'الإخلاص', transliteration: 'Al-Ikhlas', translation: 'Ikhlas', totalVerses: 4, revelation: 'Makkah' },
  { number: 113, name: 'الفلق', transliteration: 'Al-Falaq', translation: 'Waktu Subuh', totalVerses: 5, revelation: 'Makkah' },
  { number: 114, name: 'الناس', transliteration: 'An-Nas', translation: 'Manusia', totalVerses: 6, revelation: 'Makkah' },
];

export async function GET() {
  try {
    return NextResponse.json(surahs);
  } catch (error) {
    console.error('Error fetching surahs:', error);
    return NextResponse.json(
      { error: 'Failed to fetch surahs' },
      { status: 500 }
    );
  }
}
