
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.1
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.1",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  role: 'role',
  image: 'image',
  emailVerified: 'emailVerified',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  resetToken: 'resetToken',
  resetTokenExpiry: 'resetTokenExpiry',
  isActive: 'isActive',
  jabatan: 'jabatan',
  nip: 'nip',
  signatureUrl: 'signatureUrl',
  ttdUrl: 'ttdUrl',
  username: 'username',
  recoveryCodeHash: 'recoveryCodeHash',
  isRecoveryCodeSetup: 'isRecoveryCodeSetup'
};

exports.Prisma.GuruScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  nip: 'nip',
  jabatan: 'jabatan',
  bidangKeahlian: 'bidangKeahlian',
  tanggalLahir: 'tanggalLahir',
  jenisKelamin: 'jenisKelamin',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  tandaTangan: 'tandaTangan',
  mulaiMengajar: 'mulaiMengajar'
};

exports.Prisma.SiswaScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  nis: 'nis',
  kelasId: 'kelasId',
  alamat: 'alamat',
  tanggalLahir: 'tanggalLahir',
  jenisKelamin: 'jenisKelamin',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  nisn: 'nisn',
  tempatLahir: 'tempatLahir',
  statusSiswa: 'statusSiswa',
  tanggalKeluar: 'tanggalKeluar',
  kelasAngkatan: 'kelasAngkatan',
  tahunAjaranMasukId: 'tahunAjaranMasukId',
  lulusAt: 'lulusAt',
  latestJuzAchieved: 'latestJuzAchieved'
};

exports.Prisma.OrangTuaScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  pekerjaan: 'pekerjaan',
  alamat: 'alamat',
  tanggalLahir: 'tanggalLahir',
  jenisKelamin: 'jenisKelamin',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrangTuaSiswaScalarFieldEnum = {
  id: 'id',
  orangTuaId: 'orangTuaId',
  siswaId: 'siswaId',
  hubungan: 'hubungan',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TahunAjaranScalarFieldEnum = {
  id: 'id',
  nama: 'nama',
  tanggalMulai: 'tanggalMulai',
  tanggalSelesai: 'tanggalSelesai',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  semester: 'semester',
  targetHafalan: 'targetHafalan'
};

exports.Prisma.KelasScalarFieldEnum = {
  id: 'id',
  nama: 'nama',
  tahunAjaranId: 'tahunAjaranId',
  kapasitas: 'kapasitas',
  targetJuz: 'targetJuz',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  guruTahfidzId: 'guruTahfidzId'
};

exports.Prisma.GuruKelasScalarFieldEnum = {
  id: 'id',
  guruId: 'guruId',
  kelasId: 'kelasId',
  tanggalMulai: 'tanggalMulai',
  tanggalSelesai: 'tanggalSelesai',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  peran: 'peran'
};

exports.Prisma.TargetHafalanScalarFieldEnum = {
  id: 'id',
  siswaId: 'siswaId',
  kelasId: 'kelasId',
  tahunAjaranId: 'tahunAjaranId',
  targetJuz: 'targetJuz',
  targetSurah: 'targetSurah',
  targetAyat: 'targetAyat',
  deadline: 'deadline',
  keterangan: 'keterangan',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  bulan: 'bulan',
  tahun: 'tahun'
};

exports.Prisma.HafalanScalarFieldEnum = {
  id: 'id',
  siswaId: 'siswaId',
  guruId: 'guruId',
  tanggal: 'tanggal',
  juz: 'juz',
  surah: 'surah',
  ayatMulai: 'ayatMulai',
  ayatSelesai: 'ayatSelesai',
  keterangan: 'keterangan',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  surahTambahan: 'surahTambahan',
  surahNumber: 'surahNumber'
};

exports.Prisma.PenilaianScalarFieldEnum = {
  id: 'id',
  hafalanId: 'hafalanId',
  siswaId: 'siswaId',
  guruId: 'guruId',
  tajwid: 'tajwid',
  kelancaran: 'kelancaran',
  makhraj: 'makhraj',
  adab: 'adab',
  nilaiAkhir: 'nilaiAkhir',
  catatan: 'catatan',
  notifiedAt: 'notifiedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TahsinScalarFieldEnum = {
  id: 'id',
  siswaId: 'siswaId',
  guruId: 'guruId',
  tanggal: 'tanggal',
  level: 'level',
  materiHariIni: 'materiHariIni',
  bacaanDipraktikkan: 'bacaanDipraktikkan',
  catatan: 'catatan',
  statusPembelajaran: 'statusPembelajaran',
  surah: 'surah',
  ayatAwal: 'ayatAwal',
  ayatAkhir: 'ayatAkhir',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MateriTahsinScalarFieldEnum = {
  id: 'id',
  guruId: 'guruId',
  kelasId: 'kelasId',
  judul: 'judul',
  jenisMateri: 'jenisMateri',
  fileUrl: 'fileUrl',
  youtubeUrl: 'youtubeUrl',
  deskripsi: 'deskripsi',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PresensiScalarFieldEnum = {
  id: 'id',
  siswaId: 'siswaId',
  guruId: 'guruId',
  tanggal: 'tanggal',
  status: 'status',
  keterangan: 'keterangan',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PengumumanScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  judul: 'judul',
  isi: 'isi',
  tanggalMulai: 'tanggalMulai',
  tanggalSelesai: 'tanggalSelesai',
  isPinned: 'isPinned',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lampiran: 'lampiran',
  attachmentUrl: 'attachmentUrl',
  attachmentName: 'attachmentName',
  attachmentSize: 'attachmentSize',
  isPublished: 'isPublished',
  deletedAt: 'deletedAt',
  audience: 'audience'
};

exports.Prisma.PengumumanReadScalarFieldEnum = {
  id: 'id',
  pengumumanId: 'pengumumanId',
  userId: 'userId',
  closedAt: 'closedAt',
  createdAt: 'createdAt'
};

exports.Prisma.BukuDigitalScalarFieldEnum = {
  id: 'id',
  guruId: 'guruId',
  judul: 'judul',
  deskripsi: 'deskripsi',
  kategori: 'kategori',
  fileUrl: 'fileUrl',
  fileName: 'fileName',
  fileSize: 'fileSize',
  downloadCount: 'downloadCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  classId: 'classId'
};

exports.Prisma.AgendaScalarFieldEnum = {
  id: 'id',
  guruId: 'guruId',
  kelasId: 'kelasId',
  judul: 'judul',
  deskripsi: 'deskripsi',
  tanggal: 'tanggal',
  waktuMulai: 'waktuMulai',
  waktuSelesai: 'waktuSelesai',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ActivityLogScalarFieldEnum = {
  id: 'id',
  actorId: 'actorId',
  actorRole: 'actorRole',
  actorName: 'actorName',
  action: 'action',
  title: 'title',
  description: 'description',
  targetUserId: 'targetUserId',
  targetRole: 'targetRole',
  targetName: 'targetName',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.GuruActivityScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  subtitle: 'subtitle',
  actorId: 'actorId',
  actorRole: 'actorRole',
  createdAt: 'createdAt'
};

exports.Prisma.MotivasiScalarFieldEnum = {
  id: 'id',
  isi: 'isi',
  author: 'author',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AdminSignatureScalarFieldEnum = {
  id: 'id',
  type: 'type',
  jabatan: 'jabatan',
  nama: 'nama',
  signatureData: 'signatureData',
  capData: 'capData',
  capOpacity: 'capOpacity',
  capScale: 'capScale',
  capOffsetX: 'capOffsetX',
  capOffsetY: 'capOffsetY',
  fileName: 'fileName',
  fileSize: 'fileSize',
  imageWidth: 'imageWidth',
  imageHeight: 'imageHeight',
  uploadedAt: 'uploadedAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TasmiScalarFieldEnum = {
  id: 'id',
  siswaId: 'siswaId',
  jumlahHafalan: 'jumlahHafalan',
  juzYangDitasmi: 'juzYangDitasmi',
  jamTasmi: 'jamTasmi',
  tanggalTasmi: 'tanggalTasmi',
  guruPengampuId: 'guruPengampuId',
  statusPendaftaran: 'statusPendaftaran',
  catatanPenolakan: 'catatanPenolakan',
  catatan: 'catatan',
  tanggalDaftar: 'tanggalDaftar',
  tanggalUjian: 'tanggalUjian',
  guruVerifikasiId: 'guruVerifikasiId',
  guruPengujiId: 'guruPengujiId',
  nilaiKelancaran: 'nilaiKelancaran',
  nilaiTajwid: 'nilaiTajwid',
  nilaiAdab: 'nilaiAdab',
  nilaiIrama: 'nilaiIrama',
  nilaiAkhir: 'nilaiAkhir',
  predikat: 'predikat',
  catatanPenguji: 'catatanPenguji',
  pdfUrl: 'pdfUrl',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  isPassed: 'isPassed',
  assessedAt: 'assessedAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  message: 'message',
  type: 'type',
  isRead: 'isRead',
  data: 'data',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PushSubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  endpoint: 'endpoint',
  p256dh: 'p256dh',
  auth: 'auth',
  userAgent: 'userAgent',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RateLimitScalarFieldEnum = {
  id: 'id',
  key: 'key',
  attempts: 'attempts',
  lockedUntil: 'lockedUntil',
  updatedAt: 'updatedAt'
};

exports.Prisma.CertificateTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  htmlTemplate: 'htmlTemplate',
  isDefault: 'isDefault',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CertificateScalarFieldEnum = {
  id: 'id',
  type: 'type',
  tasmiId: 'tasmiId',
  awardRecipientId: 'awardRecipientId',
  certificateNumber: 'certificateNumber',
  generatedAt: 'generatedAt',
  generatedById: 'generatedById',
  templateId: 'templateId',
  status: 'status',
  fileUrl: 'fileUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WisudaEventScalarFieldEnum = {
  id: 'id',
  name: 'name',
  date: 'date',
  period: 'period',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AwardCategoryScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  groupName: 'groupName',
  categoryName: 'categoryName',
  quota: 'quota',
  reward: 'reward',
  isActive: 'isActive',
  templateId: 'templateId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AwardRecipientScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  categoryId: 'categoryId',
  studentId: 'studentId',
  sourceTasmiId: 'sourceTasmiId',
  approvedBy: 'approvedBy',
  approvedAt: 'approvedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Role = exports.$Enums.Role = {
  ADMIN: 'ADMIN',
  GURU: 'GURU',
  SISWA: 'SISWA',
  ORANG_TUA: 'ORANG_TUA'
};

exports.JenisKelamin = exports.$Enums.JenisKelamin = {
  LAKI_LAKI: 'LAKI_LAKI',
  PEREMPUAN: 'PEREMPUAN'
};

exports.StatusAkun = exports.$Enums.StatusAkun = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
  suspended: 'suspended'
};

exports.StatusSiswa = exports.$Enums.StatusSiswa = {
  AKTIF: 'AKTIF',
  LULUS: 'LULUS',
  PINDAH: 'PINDAH',
  KELUAR: 'KELUAR'
};

exports.StatusKelas = exports.$Enums.StatusKelas = {
  AKTIF: 'AKTIF',
  NONAKTIF: 'NONAKTIF'
};

exports.PeranGuru = exports.$Enums.PeranGuru = {
  utama: 'utama',
  pendamping: 'pendamping'
};

exports.LevelTahsin = exports.$Enums.LevelTahsin = {
  DASAR: 'DASAR',
  MENENGAH: 'MENENGAH',
  LANJUTAN: 'LANJUTAN'
};

exports.StatusPembelajaran = exports.$Enums.StatusPembelajaran = {
  LANJUT: 'LANJUT',
  PERBAIKI: 'PERBAIKI'
};

exports.JenisMateri = exports.$Enums.JenisMateri = {
  PDF: 'PDF',
  YOUTUBE: 'YOUTUBE',
  VIDEO: 'VIDEO'
};

exports.StatusPresensi = exports.$Enums.StatusPresensi = {
  HADIR: 'HADIR',
  IZIN: 'IZIN',
  SAKIT: 'SAKIT',
  ALFA: 'ALFA'
};

exports.KategoriBuku = exports.$Enums.KategoriBuku = {
  TAJWID: 'TAJWID',
  TAFSIR: 'TAFSIR',
  HADITS: 'HADITS',
  FIQIH: 'FIQIH',
  AKHLAK: 'AKHLAK',
  UMUM: 'UMUM',
  TAHSIN: 'TAHSIN'
};

exports.StatusTasmi = exports.$Enums.StatusTasmi = {
  MENUNGGU: 'MENUNGGU',
  DISETUJUI: 'DISETUJUI',
  DITOLAK: 'DITOLAK',
  SELESAI: 'SELESAI',
  DIBATALKAN: 'DIBATALKAN'
};

exports.CertificateType = exports.$Enums.CertificateType = {
  NON_AWARD: 'NON_AWARD',
  AWARD: 'AWARD'
};

exports.CertificateStatus = exports.$Enums.CertificateStatus = {
  GENERATED: 'GENERATED',
  REVOKED: 'REVOKED'
};

exports.Prisma.ModelName = {
  User: 'User',
  Guru: 'Guru',
  Siswa: 'Siswa',
  OrangTua: 'OrangTua',
  OrangTuaSiswa: 'OrangTuaSiswa',
  TahunAjaran: 'TahunAjaran',
  Kelas: 'Kelas',
  GuruKelas: 'GuruKelas',
  TargetHafalan: 'TargetHafalan',
  Hafalan: 'Hafalan',
  Penilaian: 'Penilaian',
  Tahsin: 'Tahsin',
  MateriTahsin: 'MateriTahsin',
  Presensi: 'Presensi',
  Pengumuman: 'Pengumuman',
  PengumumanRead: 'PengumumanRead',
  BukuDigital: 'BukuDigital',
  Agenda: 'Agenda',
  ActivityLog: 'ActivityLog',
  GuruActivity: 'GuruActivity',
  Motivasi: 'Motivasi',
  AdminSignature: 'AdminSignature',
  Tasmi: 'Tasmi',
  Notification: 'Notification',
  PushSubscription: 'PushSubscription',
  RateLimit: 'RateLimit',
  CertificateTemplate: 'CertificateTemplate',
  Certificate: 'Certificate',
  WisudaEvent: 'WisudaEvent',
  AwardCategory: 'AwardCategory',
  AwardRecipient: 'AwardRecipient'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
